### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'client_secret_ ... .apps.googleusercontent.com.json'

### ISSUE THREAD

**Issue by wisdomtooth** [mtalcott/google-photos-deduper#1]
```
 docker-compose run python python -m google_photos_deduper
time="2022-04-19T16:16:49+10:00" level=warning msg="The \"ACCESS_TOKEN\" variable is not set. Defaulting to a blank string."
[+] Running 1/0
 - Container google-photos-deduper-python-mongo-1  Running                                                                                                         0.0s
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/google_photos_deduper/__main__.py", line 64, in <module>
    run()
  File "/usr/src/app/google_photos_deduper/__main__.py", line 24, in run
    flow = Flow.from_client_secrets_file(
  File "/usr/local/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 201, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'client_secret_792370018435-b70v71v2e7cb3i3s67cdg74qtfao5a1t.apps.googleusercontent.com.json'
```

**Comment by rikkert** [comment]
You have to create an OAuth ID first here: https://console.cloud.google.com/apis/credentials
Download the OAuth client JSON file and save it in the root of this project directory.
Rename the file to `client_secret_792370018435-b70v71v2e7cb3i3s67cdg74qtfao5a1t.apps.googleusercontent.com.json` or change the filename in `google_photos_deduper/__main__.py`.
After that you can build the docker image again and now you should get the onscreen instructions to authorize the app.

**Comment by mtalcott** [comment]
Thanks for answering @rikkert
