### ISSUE TITLE
I encountered an error

### ISSUE THREAD

**Issue by newt7744** [mtalcott/google-photos-deduper#30]
![image](https://github.com/mtalcott/google-photos-deduper/assets/114227318/c348de1d-996b-4f8c-b226-95534a9ef6a7)

the log :
```
worker_1  | [2023-10-30 10:19:52,049: ERROR/ForkPoolWorker-31] Task app.tasks.process_duplicates[f30624a7-2829-4fc4-819f-dae7856e41c3] raised unexpected: RuntimeError('Expected image with 1 (grayscale), 3 (RGB) or 4 (RGBA) channels, found 2 channels.')
worker_1  | Traceback (most recent call last):
worker_1  |   File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 477, in trace_task
worker_1  |     R = retval = fun(*args, **kwargs)
worker_1  |   File "/usr/src/app/app/__init__.py", line 25, in __call__
worker_1  |     return self.run(*args, **kwargs)
worker_1  |   File "/usr/src/app/app/tasks.py", line 90, in process_duplicates
worker_1  |     results = task_instance.run()
worker_1  |   File "/usr/src/app/app/lib/process_duplicates_task.py", line 109, in run
worker_1  |     similarity_map = duplicate_detector.calculate_similarity_map()
worker_1  |   File "/usr/src/app/app/lib/duplicate_image_detector.py", line 61, in calculate_similarity_map
worker_1  |     embeddings = self._calculate_embeddings()
worker_1  |   File "/usr/src/app/app/lib/duplicate_image_detector.py", line 114, in _calculate_embeddings
worker_1  |     mp_image = mp.Image.create_from_file(storage_path)
worker_1  | RuntimeError: Expected image with 1 (grayscale), 3 (RGB) or 4 (RGBA) channels, found 2 channels.
root@googlePh:~/google-photos-deduper#

```

**Comment by newt7744** [comment]
Maybe there's something wrong with the images I'm storing, but I don't know how to deal with this

**Comment by markrichards** [comment]
I'm getting the same exact error: `Expected image with 1 (grayscale), 3 (RGB) or 4 (RGBA) channels, found 2 channels.`

Is there a way to identify the photo causing the error? If I knew which image I'd just delete it.

**Comment by mtalcott** [comment]
@markrichards @newt7744 thanks for reporting! I've merged https://github.com/mtalcott/google-photos-deduper/pull/33 which should address the issue. Please pull the latest from `main` branch and try again.

Closing this issue, feel free to reopen if this does not solve the problem.
