### ISSUE TITLE
Worker lost error

### ISSUE THREAD

**Issue by xanguera** [mtalcott/google-photos-deduper#58]
After calculating embeddings I get an error about a worker lost, with no more info on what could be the cause. Any idea how to solve it?

<img width="772" alt="image" src="https://github.com/user-attachments/assets/1acb0dd8-d34f-41bf-a1c1-2186ba9ce36c">

```
worker-1  | [2024-07-14 09:34:19,335: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 2591.')
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
worker-1  |     raise WorkerLostError(
worker-1  | billiard.einfo.ExceptionWithTraceback:
worker-1  | """
worker-1  | Traceback (most recent call last):
worker-1  |   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
worker-1  |     raise WorkerLostError(
worker-1  | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2591.
worker-1  | """
```

**Comment by rifat072** [comment]
Increase Memory Limit in docker settings
